---
- name: Installing docker for Ubuntu
  import_tasks: docker-ubuntu.yml
  when: ansible_facts['distribution'] | lower == "ubuntu"
- name: Installing docker for CentOS
  import_tasks: docker-centos.yml
  when: ansible_facts['distribution'] | lower == "centos"
